# Site
repository: EnzoAndree/enzoandree.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Enzo Guerrero-Araya
title: Phylodynamics - Epidemiology - Computational Biology - Data Scientist
email: biologoenzo@gmail.com
website: www.github.com/EnzoAndree

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: eguerreroaraya
github_username:  enzoandree
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: enzoandree
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0003-2282-7722
googlescholar_username: H6e-nbYAAAAJ

# Additional icon links
additional_links:
- title: enzoandree.cl
  icon: fas fa-globe
  url: https://enzoandree.cl
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_ega.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Enzo and I'm a Computational Biologist finishing my PhD at the Andrés Bello University in Chile. I study the genomic epidemiology, evolution, adaptation and phylogenetic relationship of _Clostridioides difficile_. As well as research experience I also have experience software development and data scientist.
content:
  - title: Softwares # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: FastMLST
        link: github.com/EnzoAndree/FastMLST
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
            Multilocus Sequence Typing (MLST) is a precise microbial typing approach at the intra-species level for epidemiologic and evolutionary purposes. It operates by assigning a sequence type (ST) identifier to each specimen, based on a combination of alleles of multiple housekeeping genes included in a defined scheme. The use of MLST has multiplied due to the availability of large numbers of genomic sequences and epidemiologic data in public repositories. However, data processing speed has become problematic due to the massive size of modern datasets. Here, we present FastMLST, a tool that is designed to perform PubMLST searches using BLASTn and a divide-and-conquer approach that processes each genome assembly in parallel. The output offered by FastMLST includes a table with the ST, allelic profile, and clonal complex or clade (when available), detected for a query, as well as a multi-FASTA file or a series of FASTA files with the concatenated or single allele sequences detected, respectively. FastMLST was validated with 91 different species, with a wide range of guanine-cytosine content (%GC), genome sizes, and fragmentation levels, and a speed test was performed on 3 datasets with varying genome sizes. Compared with other tools such as mlst, CGE/MLST, MLSTar, and PubMLST, FastMLST takes advantage of multiple processors to simultaneously type up to 28 000 genomes in less than 10 minutes, reducing processing times by at least 3-fold with 100% concordance to PubMLST, if contaminated genomes are excluded from the analysis. The source code, installation instructions, and documentation of FastMLST are available at https://github.com/EnzoAndree/FastMLST


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fundación Ciencia & Vida
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: February 2020 to present
        description: | # this will include new lines to allow paragraphs
            I was a data scientist. The responsibilities were performing data preparation,  data mining, data visualization, and data analysis in COVID-19 pandemic-related data.
      - layout: left
        title: Andrés Bello University
        # link_text: boringcompany.com
        sub_title: Professor
        caption: March 2017 to July 2017
        description: | # this will include new lines to allow paragraphs
            I was a professor of the Laboratory of Genetic Engineering in Microorganisms (BIT200).
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Andrés Bello University
        caption: 2018 to present
        sub_title: Doctor of Philosophy
        description: | # this will include new lines to allow paragraphs
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.
      - layout: left
        title: Andrés Bello University
        caption: 2012 to 2016
        sub_title: Bachelor of Biotechnology
        description: | # this will include new lines to allow paragraphs
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.
  - title: Publications - Published # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
        FastMLST: A multi-core tool for multilocus sequence typing of draft genome assemblies
        Enzo Guerrero-Araya*, Marina Muñoz, César Rodríguez, Daniel Paredes-Sabja*. Bioinformatics and biology insights - 2021. * co-corresponding authors
        I performed the design, software development, testing, implementation of FastMLST, and drafted the manuscript.
        Evolution and epidemic spread of SARS-CoV-2 in Colombia: A year into the pandemic
        Sergio Castañeda, Luz H Patiño, Marina Muñoz, Nathalia Ballesteros, Enzo Guerrero-Araya, Daniel Paredes-Sabja, Carolina Flórez, Sergio Gomez, Carolina Ramírez-Santana, Gustavo Salguero, Juan E Gallo, Alberto E Paniz-Mondolfi, Juan David Ramírez. Vaccines - 2021.
        I performed the calculation of the effective reproductive number (Re) of SARS-CoV-2 over time in Colombia,  and assisted in writing the manuscript and interpreting the results.
        Major genetic discontinuity and novel toxigenic species in Clostridioides difficile taxonomy
        Daniel R Knight, Korakrit Imwattana, Brian Kullin, Enzo Guerrero-Araya, Daniel Paredes-Sabja, Xavier Didelot, Kate E Dingle, David W Eyre, César Rodríguez, Thomas V Riley. Elife - 2021.
        I performed the Bayesian evolutionary analysis of the isolates, the molecular dating, to search for the presence of C. difficile toxins in the genomes together with analysis of their genomic context, and assisted in writing the manuscript and interpreting the results.
        Comprehensive genome analyses of Sellimonas intestinalis, a potential biomarker of homeostasis gut recovery
        Marina Muñoz, Enzo Guerrero-Araya, Catalina Cortés-Tapia, Angela Plaza-Garrido, Trevor D Lawley, Daniel Paredes-Sabja. Microbial genomics - 2020.
        I performed the Bayesian evolutionary analysis of the isolates, annotation of the proteins using Clusters of Orthologous Groups, and assisted in writing the manuscript and interpreting the results.
        The Clostridioides difficile Cysteine-Rich Exosporium Morphogenetic Protein, CdeC, Exhibits Self-Assembly Properties That Lead to Organized Inclusion Bodies in Escherichia coli
        Alba Romero-Rodríguez, Scarlett Troncoso-Cotal, Enzo Guerrero-Araya, Daniel Paredes-Sabja. Msphere - 2020.
        I performed the evolutionary analysis of CdeC as well all bioinformatics methods, designed their figures, assisted in writing the manuscript and interpreting the results.
        Origin, genomic diversity and microevolution of the Clostridium difficile B1/NAP1/RT027/ST01 strain in Costa Rica, Chile, Honduras and Mexico
        Enzo Guerrero-Araya, Claudio Meneses, Eduardo Castro-Nallar, Ana M. Guzmán D., Manuel Álvarez-Lobos, Carlos Quesada-Gómez, Daniel Paredes-Sabja, César Rodríguez. Microbial genomics - 2020.
        I performed the assembly, annotation, and evolutionary analysis of isolates as well as all bioinformatics methods, prepared figures  and tables, and drafted the manuscript.
        Clostridium difficile exosporium cysteine-rich proteins are essential for the morphogenesis of the exosporium layer, spore resistance, and affect C. difficile pathogenesis
        Paulina Calderon-Romero, Pablo Castro-Cordova, Rodrigo Reyes-Ramirez, Mauro Milano-Cespedes, Enzo Guerrero-Araya, Marjorie Pizarro-Guajardo, Valeria Olguin-Araneda, Fernando Gil, Daniel Paredes-Sabja. PLoS pathogens - 2018.
        I performed the evolutionary analysis of cysteine-rich proteins as well all bioinformatics methods, designed their figures, assisted in writing the manuscript and interpreting the results.
        Genome sequence of Clostridium paraputrificum 373-A1 isolated in Chile from a patient infected with Clostridium difficile
        Enzo Guerrero-Araya, Angela Plaza-Garrido, Fernando Díaz-Yañez, Marjorie Pizaro-Guajardo, Sandro L Valenzuela, Claudio Meneses, Fernando Gil, Eduardo Castro-Nallar, Daniel Paredes-Sabja. Genome Announcements - 2016.
        I performed the assembly, identification, and annotation of the bacterial isolate, prepared figures and tables, and drafted the manuscript.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
